### PR TITLE
Added and Changed certain items

### PR DESCRIPTION
**Pull request by BillsLate**
Added assorted barrows items, Changed Dart animation, Added dragon knife special attack and lastly blazing blowpipe + venator bow

### CODE REVIEW

**Comment by ngraves95** [comment]
Thanks for the PR - can you please reword the commit message to contain all of the information in your comment?

**Comment by BillsLate** [comment]
I think that may have worked? sorry new at this whole thing

**Comment by ngraves95** [comment]
I want to remove the 'ur nan' commit and only have the contents and message for 6a6ab59f3c3f0b7091fbe960fea4a6a17e59a12c. Try doing something like this: `git reset --soft HEAD~3 ; git commit -m 'Added assorted barrows items, Changed Dart animation, Added dragon knife special attack and lastly blazing blowpipe + venator bow'`

**Comment by BillsLate** [comment]
I am going to close this real quick and just restart. that did not work

**Pull request closed without merging**
