### PR TITLE
Added items

### PR DESCRIPTION
**Pull request by BillsLate**
Added assorted barrows items, Changed Dart animation, Added dragon knife special attack and lastly blazing blowpipe + venator bow. Sorry about that

### CODE REVIEW

**Comment by BillsLate** [comment]
I forgot to push the darts change as well whenever i restarted it

**Comment by ngraves95** [comment]
Can you squash this into one commit and get rid of the 3 "changed darts as well" commits?

**Comment by BillsLate** [comment]
I have 0 clue how to do that man

**Comment by ngraves95** [comment]
Alright, I'll merge it and fix it up on my end.

**Pull request merged**
