### PR TITLE
Many Improvements

### PR DESCRIPTION
**Pull request by Lexer747**
Changes how "isPlayerAttacking" works to be target based rather than purely animation based. Animations are still used for various things but this makes the plugin a bit more robust to future updates that use generic weapons with no funny dynamic attack speeds. 4 tick staves will still also need to be manually updated but this is a step in the right direction.

* Add Valarmore animations
  * Dual Macuahuitl (and spec) 
    * Blood moon set effect (1 tick reduction)
  * Blue Moon Spear (and spec) (set effect doesn't affect ticks)
  * Atlatl (and spec)
  * Tonalztics (and spec)

* Elder maul heavily inspired by (https://github.com/ngraves95/attacktimer/pull/49)
* Blister wood heavily inspired by (https://github.com/ngraves95/attacktimer/pull/51)
* 4 Tick staves:
  * Sang & Kit
  * Trident enchanced (Swamp too)
  * Accursed Sceptre (and spec)
  * CG staves
* Dhin's (spec is the same as auto)

## Misc specs:
* Web weaver spec
* Ursine chainmace spec
* Bone dagger spec
* Dscim spec
* D2H spec
* Ancient Mace spec
* Arclight spec
* Sara sword spec
* Red keris (doesn't do proper hit detection yet, can come in another PR)
* Bludgeon spec
* Barrel chest anchor spec
* Rune claws
* Ballista spec (shared with heavy and light)
* Rune thrown axe

-----

Full transparency, this originally came out of fork I created because the sang (5t) fix has been so slow to get fixed I wanted to dip my toes into plugin dev and see if I could figure things out. Turns out this is not hard to fix - your plugin is a sweet baseline, and other people had even come before me in March with reasonable small diff PRs to fix it, alas they remain un-merged. Therefore I started with a fork. 

However as it was pointed out by the runelite team it's worth trying to [only have one plugin](https://github.com/runelite/plugin-hub/pull/6207#issuecomment-2184283486) rather than two versions of the same thing, given that I have not diverged very much from the original - I agree.

So this is my ernest attempt to get fixes merged and upstreamed back to runelite without the need for a second version of this plugin :)

I hope you'll review this soon, let me know if there's any style/guidelines I've missed.

## Testing

https://youtu.be/S3gjOvCfy2k

(Note I didn't record some testing and now I've sold those weapons, but be assured everything on the list was tested atleast once)

### CODE REVIEW

**Comment by Lexer747** [comment]
@ngraves95 can you take a look at this patch please? I'd really like these fixes, elder and sang especially.

**Comment by ngraves95** [comment]
Sorry about the long response time. I have been quite busy but I'm very excited with the looks of your change log. I'll work on getting this merged and upstreamed. Thanks in advance!

**Comment by ngraves95** [comment]
Created a PR to submit this here: https://github.com/runelite/plugin-hub/pull/6223. Again, thank you for your work on this.

**Comment by Lexer747** [comment]
Glad to see you're still active! Thank you for the merge <3

I'll work on getting a well written second PR for a few other weapons and fixes I've been cooking: Harm & spellbook detection, Red Keris, and 0-ticking swaps.

**Pull request merged**
