### PR TITLE
AnimationData.java

### PR DESCRIPTION
**Pull request by cdog2323**
Added Soulreaper Axe animation for slash and slash spec.

### CODE REVIEW

**Comment by cdog2323** [comment]
Let me know @ngraves95

**Comment by ngraves95** [comment]
Did you mean to close this PR? Looks fine to me - I'll merge if you re-open it.

**Comment by cdog2323** [comment]
Oh woops. Yeah I'll re-open

**Comment by cdog2323** [comment]
@ngraves95  https://github.com/ngraves95/attacktimer/pull/30

I made a new one since I couldn't re-open this.

**Pull request closed without merging**
